LojaSquare:
  Debug: true
  # A opcao Smart_Delivery funciona da seguinte forma:
  # Se o Smart_Delivery estiver marcado como true, e um player comprar 10 Vips no site. Ao inves de o plugin executar 10x o 
  # comando que voce colocou, sera executado apenas 1x com a quantidade 10 embutida no placeholder @qnt
  # (@qnt fica la nos comandos dos grupos, ali em baixo).
  # Ou seja, o plugin sera inteligente e executara menos comandos, realizando a entrega e trazendo um melhor desempenho.
  # Se o Smart_Delivery estiver marcado como false, o plugin ira executar 10x o comando que voce colocou 
  # (ou a quantidade de vezes que o player comprou). Entao se voce tiver pacote de cash e o player comprar 500 pacotes de cash, o
  # plugin ira executar 500x os comandos de entrega do cash.
  # Ai vai depender de como voce prefere a entrega. Recomendamos deixar true.
  Smart_Delivery: true
  # Para saber o que deve ser inserido em Key_API e em Servidor, acesse este tutorial:
  # https://painel.lojasquare.com.br/faq/ver?id=9
  # (E necessario fazer login para ver o tutorial)
  Key_API: "lojasquare-key-api"
  Servidor: "Nome-Do-Servidor"
  Connection_Timeout: 1500
  Read_Timeout: 3000

Config:
  HTTPS: true
  # A cada X segundos sera checado no site se tem algum item para ser entregue. (Para nao precisar do player relogar)
  Tempo_Checar_Compras: 60

Grupos:
  # Com relacao a configuracao de DISPUTA e RESOLVIDO, veja o tutorial: https://painel.lojasquare.com.br/faq/ver?id=10
  #Nao mude o nome deste grupo. Se o player abrir uma disputa com voce, o LojaSquare usara este grupo para aplicar uma punicao.
  DISPUTA:
    #O comando abaixo e o comando do TGVIP. As variaveis do LojaSquare sao:
    # @player = Player que comprou
    # @qnt    = quantidade que foi adquirida pelo player
    # @grupo  = Grupo que voce configurou para o pacote no seu painel. Neste caso, VIPFerro
    # @dias   = Quantidade de dias que voce configurou para o pacote no seu painel.
    # Se este grupo de item NAO DER money para o player, deixe marcado como false.
    Money: false
    Cmds_A_Executar:
      # Neste exemplo o console executara o comando para gerar um vip para o player, do grupo VIPFerro, com 30 dias de duracao
      # e a key VIP podera ser usada de acordo com a @qnt que o player tiver compro no site.
      - 'ban @player &cEncerre o pedido de disputa e voce sera desbanido!'
  #Nao mude o nome deste grupo. Se o player encerrar a disputa a seu favor, o LojaSquare usara este grupo para remover a punicao.
  RESOLVIDO:
    #O comando abaixo e o comando do TGVIP. As variaveis do LojaSquare sao:
    # @player = Player que comprou
    # @qnt    = quantidade que foi adquirida pelo player
    # @grupo  = Grupo que voce configurou para o pacote no seu painel. Neste caso, VIPFerro
    # @dias   = Quantidade de dias que voce configurou para o pacote no seu painel.
    # Se este grupo de item NAO DER money para o player, deixe marcado como false.
    Money: false
    Cmds_A_Executar:
      # Neste exemplo o console executara o comando para gerar um vip para o player, do grupo VIPFerro, com 30 dias de duracao
      # e a key VIP podera ser usada de acordo com a @qnt que o player tiver compro no site.
      - 'desban @player'
  # Para configurar os outros produtos, veja o tutorial: https://painel.lojasquare.com.br/faq/ver?id=15
  #Nome do Grupo do produto que voce criou no seu painel do LojaSquare.
  VIPFerro:
    #O comando abaixo e o comando do TGVIP. As variaveis do LojaSquare sao:
    # @player = Player que comprou
    # @qnt    = quantidade que foi adquirida pelo player
    # @grupo  = Grupo que voce configurou para o pacote no seu painel. Neste caso, VIPFerro
    # @dias   = Quantidade de dias que voce configurou para o pacote no seu painel.
    # Se este grupo de item NAO DER money para o player, deixe marcado como false.
    Ativar_Com_Player_Offline: false
    Enviar_Mensagem: false
    Mensagem_Receber_Ao_Ativar_Produto:
      - '&eOla, &a@player'
      - '&eO produto que voce adquiriu (&a@produto) foi ativado!'
      - '&eDias: &a@dias'
      - '&eQuantidade: &a@qnt'
    Money: false
    Cmds_A_Executar:
      # Neste exemplo o console executara o comando para gerar um vip para o player, do grupo VIPFerro, com 30 dias de duracao
      # e a key VIP podera ser usada de acordo com a @qnt que o player tiver compro no site.
      # Recomendamos que use o TGVIP e NAO utilize o comando /darvip.
      # Explicacao na FAQ: https://painel.lojasquare.com.br/faq/ver?id=18
      - 'gerarvip @grupo @dias @qnt @player'
  #Nome do Grupo do produto que voce criou no seu painel do LojaSquare.
  Cash10:
    # Quando o produto for entregue devera mandar uma mensagem ao player que o recebeu?!
    Enviar_Mensagem: false
    # Mensagem que o player que recebeu o produto ira receber tambem.
    Mensagem_Receber_Ao_Ativar_Produto:
      - '&eOla, &a@player'
      - '&eO produto que voce adquiriu (&a@produto) foi ativado!'
      - '&eDias: &a@dias'
      - '&eQuantidade: &a@qnt'
    # Se a quantidade de produtos que o player tiver compro for igual a 1, ele ira ganhar 10 cash.
    # Se a quantidade de produtos que o player tiver compro for igual a 4, ele ira ganhar 10x5 cash = 50 cash
    Quantidade_De_Money: 10
    Ativar_Com_Player_Offline: false
    # Se este grupo de item DER Money para o player (CASH/almas tambem sao tipos de money money), deixe como true
    Money: true
    Cmds_A_Executar:
      # Neste exemplo o console executara o comando para dar a quantidade de money adquirida ao player.
      # Se o player tiver adquirido 2 quantidades do grupo Cash10, ele recebera 10x2 = 20 cashs.
      # Ou seja, a variavel @money sera igual a 20.00
      # Se voce usar algum plugin que nao aceita valores quebrados (Exemplo: 1.05), utilize esta variavel: @moneyInteiro
      # Ao utilizar @moneyInteiro, voce deixara de receber como valor 20.00 e recebera 20 apenas.
      - 'money give @player @money'

Msg:
  Produto_Nao_Configurado: "&4[LojaSquare] &cVoce tem um produto para ser entregue, porem, o grupo do produto nao esta configurado. Grupo: &a@grupo"
